INSERT INTO APARTMENT (APARTMENT_NUMBER, APARTMENT_CLASS)
        VALUES ( 101, 'LUXURY' );
INSERT INTO APARTMENT (APARTMENT_NUMBER, APARTMENT_CLASS)
        VALUES ( 102, 'CHEAP' );
INSERT INTO APARTMENT (APARTMENT_NUMBER, APARTMENT_CLASS)
        VALUES ( 105, 'MEDIUM' );

Insert into Resident (FIRSTNAME, LASTNAME, EMAIL, ARRIVAL_TIME, DEPARTURE_TIME, APARTMENT_ID)
    values('Stephen', 'King', 'stephenking@test.com', '2021-03-13', '2021-04-10', 1);
Insert into Resident (FIRSTNAME, LASTNAME, EMAIL, ARRIVAL_TIME, DEPARTURE_TIME, APARTMENT_ID)
    values('Margaret', 'Mitchell', 'margaretmitchell@test.com', '2020-10-26', '2021-04-10', 2);